#%RAML 0.8

title: music-api
baseUri: http://localhost:7474/music-api
version: v0.1.0
mediaType: application/json

/play:
  description: |
        Plays current song in playlist, or a song file from 
        the provided path, for an optional duration in seconds.
  post:
    body:
      example: |  
        { 
          "songPath":"chiptunes/8bp059/8bp059-05-bit_shifter-reformat_the_planet.mp3",
          "secondsToPlay": 14 
        }
    responses:
      200:
        body:
          example: !include current_song_info.example.json 
# this error is handled by mipod api and get's forwarded automatically 
# by restify's error handler. Gets sent as a code 500 InternalServer error.
#      422:
#        body:
#          example: | 
#            { "error":"couldn't find song at <songPath>" }

/pause:
  description: pause current song
  post:
    responses:
      200:
        body:
          example: | 
            { "message":"paused current song" }

/stop:
  description: stop current song
  post:
    responses:
      200:
        body:
          example: | 
            { "message":"stopped current song" }

/current:
  description: Returns current song info
  get:
    responses:
      200:
        body:
          example: !include current_song_info.example.json 
      404:
        description: Nothing is currently playing



